# -*- coding: utf-8 -*-
"""OPERADORES DE IDENTIDADE

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1LWkouQ84GBgEnq6LzEzD742zKI9y0Cet
"""

x1="botafogo"
x2="flamengo"
x3="botafogo"

xresult_1 = x1 is x3
xresult_2 = x1 is not x2
xresult_3 = x1 is x2
xresult_4 = x2 is not x3

print(xresult_1)
print(xresult_2)
print(xresult_3)
print(xresult_4)

frutas=["banana","laranja","uva","abacaxi"]

x1="banana"
x2="laranja"
x3="abacaxi"

xresult_1 = x1 in frutas
xresult_2 = x1 not in frutas
xresult_3 = x2 not in frutas
xresult_4 = x3 in frutas

print(xresult_1)
print(xresult_2)
print(xresult_3)
print(xresult_4)

x=4
x1=9
x2=5

xresult = (((2+5)*3)+x+5)<x1
print(xresult)

x=4
x1=9
x2=5

xresult = ((2+5*3)+(x+5<x1)==(x==6+x2*2))
print(xresult)

x=4
x1=9
x2=5

xresult= (((3*6)+x-3)<x2)
print(xresult)

x=4
x1=9
x2=5

xresult = (((7*8)>(x+4-x1)<(x*2+x2*9)))
print(xresult)

